### ISSUE TITLE
feat: decide on method to support multiple versions

### ISSUE THREAD

**Issue by castrojo** [ublue-os/base#65]
Now that we've got the versions sorted it'd be nice if we got some recommendations from folks on how we should best handle the containerfile and associated files. This image is relatively simple so I don't expect us to have something complex. 

However downstream images might be doing more complex tasks, for example I make deeper changes in the ubuntu image (different/new packages, changes in others depending those packages, etc).  So let's set a method in this image so the others can just grab this action. 

Fedora supports only three versions at a time, so I've been thinking something like

```
Containerfile.36
Containerfile.37 
Containerfile.38
```

That seems straightforward and easier to contextually switch from than templating out one Containerfile. For the rest of the files in the repo I think we can version them, something like`COPY 37/etc /etc` and then `COPY 38/etc /etc`  

Then the root of the repo would look like this. 

```
36
37
38
Containerfile.36
Containerfile.37 
Containerfile.38
```

Is this a smart way to do it or is going with one Containerfile the way to go? cc @animeshn99

**Comment by animeshn99** [comment]
The folder structure will contain all 37 38 39 folders only.. and we can manage the folder no inside container file with arguments that can be pass during container build.
So we will have only one container file and multiple version folder

**Comment by castrojo** [comment]
Sounds good to me, feel free to self-assign, and thanks for your feedback!

**Comment by animeshn99** [comment]
Welcome... I will do it by tomorrow

**Comment by animeshn99** [comment]
I have created an PR. Please check and i am not able to assign myself. Can you help me on how to do that?

**Comment by aguslr** [comment]
> The folder structure will contain all 37 38 39 folders only.. and we can manage the folder no inside container file with arguments that can be pass during container build. So we will have only one container file and multiple version folder

I have done something in https://github.com/aguslr/bluevanilla/commit/f664d53db64ac264ed9f60ed159f74376bef6844 so that each major version has their own directory with a `rootfs` subdirectory and a `Containerfile`.

Then it's just a matter of changing the GitHub Action to something like:

```
- name: Build Image
  id: build_image
  uses: redhat-actions/buildah-build@v2
  with:
    context: |
      ./fc${{ matrix.major_version }}
    containerfiles: |
      ./fc${{ matrix.major_version }}/Containerfile
    build-args: |
      FEDORA_MAJOR_VERSION=${{ matrix.major_version }}
```

At the moment, both directories contain pretty much the same but, since I'm using systemd services to add an unfiltered FlatHub repo and to replace Fedora's flatpaks with FlatHub's which [might no longer be necessary for Silverblue 38][1], I rather have separate configurations.

It would be nice to have a way to share most of the common stuff between versions though.


[1]: https://fedoraproject.org/wiki/Changes/UnfilteredFlathub

**Comment by castrojo** [comment]
Let's go ahead and close this and concentrate on `main`, thanks for the discussion everyone!
